# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("browser.cache.disk.capacity", 644028);
user_pref("consoleservice.enabled", true);
user_pref("device.storage.writable.name", "sdcard");
user_pref("dom.mms.requestStatusReport", false);
user_pref("dom.mms.retrieval_mode", "automatic-home");
user_pref("dom.mozApps.used", true);
user_pref("dom.sms.requestStatusReport", false);
user_pref("gecko.buildID", "20130820030722");
user_pref("gecko.mstone", "26.0a1");
user_pref("idle.lastDailyNotification", 1377300355);
user_pref("intl.accept_languages", "en-US, en");
user_pref("layers.offmainthreadcomposition.log-animations", false);
user_pref("marionette.contentListener", false);
user_pref("marionette.force-local", false);
user_pref("ril.mms.mmsc", "");
user_pref("ril.mms.mmsport", 0);
user_pref("ril.mms.mmsproxy", "");
user_pref("ril.radio.disabled", false);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.telemetry.previousBuildID", "20130820030722");
user_pref("layout.css.devPixelsPerPx", "3.0");
